// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.DAL.EF;

#nullable disable

namespace StudentManagement.DAL.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20260114170140_RebuildDatabase")]
    partial class RebuildDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Entities.Models.Classroom", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClassId");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ClassName = "CNTT_K15",
                            FacultyName = "Công nghệ thông tin"
                        },
                        new
                        {
                            ClassId = 2,
                            ClassName = "QTKD_K15",
                            FacultyName = "Quản trị kinh doanh"
                        });
                });

            modelBuilder.Entity("StudentManagement.Entities.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            Score = 8.5,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            GradeId = 2,
                            Score = 7.0,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            GradeId = 3,
                            Score = 9.0,
                            StudentId = 2,
                            SubjectId = 1
                        });
                });

            modelBuilder.Entity("StudentManagement.Entities.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("StudentId");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Address = "Hà Nội",
                            ClassId = 1,
                            DateOfBirth = new DateTime(2003, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Văn A",
                            Gender = true,
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            StudentId = 2,
                            Address = "Đà Nẵng",
                            ClassId = 1,
                            DateOfBirth = new DateTime(2003, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trần Thị B",
                            Gender = false,
                            PhoneNumber = "0912345678"
                        });
                });

            modelBuilder.Entity("StudentManagement.Entities.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Credits = 4,
                            SubjectName = "Lập trình C#"
                        },
                        new
                        {
                            SubjectId = 2,
                            Credits = 3,
                            SubjectName = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            SubjectId = 3,
                            Credits = 2,
                            SubjectName = "Tiếng Anh chuyên ngành"
                        });
                });

            modelBuilder.Entity("StudentManagement.Entities.Models.Grade", b =>
                {
                    b.HasOne("StudentManagement.Entities.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagement.Entities.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentManagement.Entities.Models.Student", b =>
                {
                    b.HasOne("StudentManagement.Entities.Models.Classroom", "Classroom")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("StudentManagement.Entities.Models.Classroom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManagement.Entities.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("StudentManagement.Entities.Models.Subject", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
